### ISSUE TITLE
Cannot reproduce the results on VL-Checklist

### ISSUE THREAD

**Issue by hiker-lw** [lezhang7/Enhance-FineGrained#12]
hello, thanks for your wonderful work! I cannot reproduce the result on VL-checklist using your provided checkpoint.
The finegrained results I get are as follow:
```
VL_checklist Relation: action (0.7833), spatial (0.7238), average (0.7535) 
VL_checklist Attribute: action (0.7733), color (0.7729), material (0.8091), size (0.6823), state (0.6828), average (0.7441)
VL_checklist Object: location (0.8121), size (0.7984), average (0.8053)
```

**Comment by lezhang7** [comment]
Hello,

Thank you for your interest. Indeed, we do not recommend evaluating on VL-CheckList, as it comprises multiple datasets, many of which have missing samples. As indicated by your results, you achieved a higher Relation score (75.4 compared to the reported 71.8) and a higher Attribute score (74.4 compared to the reported 72.6), but a lower Object score (80.5 compared to 78.5). So far we recommend sugarcrepe as it resolve certain concerns in other dataset and is easy to run thanks to author's good codebase

Best

**Comment by lezhang7** [comment]
It is CE-CLIP, aiming for directly comparing with NegCLIP. You should be
able to reproduce results on ARO and Sugarcrepe.

hiker-lw ***@***.***>于2024年3月30日 周六上午9:59写道：
