### ISSUE TITLE
training epoch

### ISSUE THREAD

**Issue by hiker-lw** [lezhang7/Enhance-FineGrained#13]
I'm curious about the number of epochs your training process involved. According to the paper, it states that the model was trained for 5 epochs; however, in your training script, it appears that the training was actually performed for 10 epochs. This discrepancy has left me somewhat puzzled. I would greatly appreciate it if you could take a moment to explain this. Thank you!

**Comment by lezhang7** [comment]
For ce-clip, it is indeed training for 5 epochs , more training steps dosen't provide higher performance.

The training script is update for 10 epochs because we are testing another project, but to reproduce ce-clip, you can modify the script to 5 epoch.

**Comment by hiker-lw** [comment]
Thanks for your swift reply, I get it!
