### ISSUE TITLE
total datasize after augmentation/training dataset

### ISSUE THREAD

**Issue by hiker-lw** [lezhang7/Enhance-FineGrained#14]
Hello～ I'd like to know how many samples there are after conducting data augmentation on the text? Could you share the dataset you used for training (after augmentation)? Thank you very much!

**Comment by lezhang7** [comment]
Hi, since we only generating hard negative texts, so the number of images remain the same as coco2014-train split. For each image-text pair from coco, we generate 4 hard negative texts, so the total number of texts are 5 times larger than original coco2014 train split.

**Comment by hiker-lw** [comment]
Thanks for your reply!!! Can you share the augmented dataset? I would greatly appreciate it！

**Comment by lezhang7** [comment]
We provide a detailed script for automatically generating used hard negative dataset at https://github.com/lezhang7/Enhance-FineGrained/blob/main/data/prepare_dataset.sh

**Comment by hiker-lw** [comment]
> We provide a detailed script for automatically generating used hard negative dataset at https://github.com/lezhang7/Enhance-FineGrained/blob/main/data/prepare_dataset.sh

thanks~
