### ISSUE TITLE
dataset-type npy

### ISSUE THREAD

**Issue by invhun** [lezhang7/Enhance-FineGrained#18]
Hello, I’m having an issue with bash run_multiple_nodes.sh. I can’t find a class for the dataset type npy in /src/training/data.py. Could you help me out?

**Comment by xiaoxing2001** [comment]
Hi, the branch cvpr have the dataset npy： https://github.com/lezhang7/Enhance-FineGrained/blob/cvpr/src/training/data.py#L421

**Comment by invhun** [comment]
Thank you for your rapid response
